allowBuilds:
  electron: true
  electron-winstaller: false
  ffmpeg-static: true
  onnxruntime-node: true
  sharp: true
verifyDepsBeforeRun: warn
packageImportMethod: hardlink
overrides:
  onnxruntime-node: 1.27.0
  sharp: 0.35.4
