export const enum IpcChannelName {
  LibraryRead = "library:read",
  LibrarySave = "library:save",
  TagOrganizationPreview = "tags:organization-preview",
  TagOrganizationApply = "tags:organization-apply",
  TagOrganizationUndo = "tags:organization-undo",
  LibrarySyncWorks = "library:sync-works",
  PromptList = "prompt:list",
  PromptCreate = "prompt:create",
  PromptUpdate = "prompt:update",
  PromptDelete = "prompt:delete",
  PromptCopy = "prompt:copy",
  PromptFavorite = "prompt:favorite",
  PromptDuplicate = "prompt:duplicate",
  PromptCreateMany = "prompt:create-many",
  PromptClipboardRead = "prompt:clipboard-read",
  PromptContentImageChoose = "prompt:content-image-choose",
  PromptContentImageSave = "prompt:content-image-save",
  PromptAccountRead = "prompt:account-read",
  PromptReorder = "prompt:reorder",
  PromptMoveToCategory = "prompt:move-to-category",
  PromptCategoryList = "prompt:category-list",
  PromptCategoryCreate = "prompt:category-create",
  PromptCategoryUpdate = "prompt:category-update",
  PromptCategoryDelete = "prompt:category-delete",
  PromptCategoryReorder = "prompt:category-reorder",
  PromptCategoryMerge = "prompt:category-merge",
  PromptExport = "prompt:export",
  PromptImport = "prompt:import",
  PromptGithubProjectFetch = "prompt:github-project-fetch",
  TodoList = "todo:list",
  TodoCalendarRead = "todo:calendar-read",
  TodoCalendarUpdate = "todo:calendar-update",
  TodoHolidayYear = "todo:holiday-year",
  TodoTaskCreate = "todo:task-create",
  TodoTaskUpdate = "todo:task-update",
  TodoTaskDelete = "todo:task-delete",
  TodoTaskComplete = "todo:task-complete",
  TodoLibraryReplace = "todo:library-replace",
  TodoImportFiles = "todo:import-files",
  TodoExport = "todo:export",
  TodoImportLibraries = "todo:import-libraries",
  TodoProjectCreate = "todo:project-create",
  TodoProjectUpdate = "todo:project-update",
  TodoProjectDelete = "todo:project-delete",
  TodoProjectReorder = "todo:project-reorder",
  TodoWidgetCreate = "todo:widget-create",
  TodoWidgetUpdate = "todo:widget-update",
  TodoWidgetDelete = "todo:widget-delete",
  TodoWidgetReorder = "todo:widget-reorder",
  LibraryViewSettingsRead = "library:view-settings-read",
  LibraryViewSettingsSave = "library:view-settings-save",
  ThemeBackgroundChoose = "theme-background:choose",
  ThemeBackgroundRemove = "theme-background:remove",
  LibraryRootsList = "library:roots-list",
  LibraryRootOrderSet = "library:root-order-set",
  LibraryRootChooseAndScan = "library:root-choose-and-scan",
  LibraryDirectoryChooseAndImport = "library:directory-choose-and-import",
  LibraryRootScan = "library:root-scan",
  LibraryRootRemap = "library:root-remap",
  LibraryRootRemove = "library:root-remove",
  LibraryRootPurgeMissing = "library:root-purge-missing",
  LibraryRootWatchSet = "library:root-watch-set",
  LibraryExternalChanged = "library:external-changed",
  LibraryExternalValidate = "library:external-validate",
  StartupGalleryList = "startup-gallery:list",
  StartupGalleryImport = "startup-gallery:import",
  StartupGalleryImportFromClipboard = "startup-gallery:import-from-clipboard",
  StartupGalleryRemove = "startup-gallery:remove",
  StartupGalleryReset = "startup-gallery:reset",
  ImageImportFiles = "image:import-files",
  ImageImportBuffers = "image:import-buffers",
  ImageImportGenerated = "image:import-generated",
  ImageImportFilesForItem = "image:import-files-for-item",
  ImageImportProgress = "image:import-progress",
  ImageImportCancel = "image:import-cancel",
  WordDocumentImport = "word:import-document",
  ImageImportFromClipboard = "image:import-from-clipboard",
  ImageImportClipboardForItem = "image:import-clipboard-for-item",
  ImageRemoteMaterialDownload = "image:remote-material-download",
  ImageCopy = "image:copy",
  ImageExport = "image:export",
  ImageThumbnailResolve = "image:thumbnail-resolve",
  ImageThumbnailsResolve = "image:thumbnails-resolve",
  ImageGetFileSize = "image:get-file-size",
  ClipboardWriteText = "clipboard:write-text",
  ClipboardReadText = "clipboard:read-text",
  ClipboardReadImage = "clipboard:read-image",
  CanvasReferenceImageSave = "canvas:reference-image-save",
  CanvasReferenceImageRead = "canvas:reference-image-read",
  CanvasReferenceImageRemove = "canvas:reference-image-remove",
  LexiconImageImport = "lexicon:image-import",
  LexiconExport = "lexicon:export-json",
  LexiconImport = "lexicon:import-json",
  ItemDelete = "item:delete",
  VideoFramesGenerate = "video:frames-generate",
  VideoReferenceImagesImport = "video:reference-images-import",
  VideoReferenceImageDelete = "video:reference-image-delete",
  VideoReferenceImageImportClipboard = "video:reference-image-import-clipboard",
  VideoReferenceImageImportUrl = "video:reference-image-import-url",
  ArchiveExportZip = "archive:export-zip",
  ExportProgress = "export:progress",
  ArchiveImportZip = "archive:import-zip",
  AiSettingsRead = "ai:settings-read",
  AiSettingsSave = "ai:settings-save",
  AiSettingsExport = "ai:settings-export",
  AiSettingsImport = "ai:settings-import",
  AiSettingsImportApply = "ai:settings-import-apply",
  AiApiKeyCopy = "ai:api-key-copy",
  AiApiKeyRead = "ai:api-key-read",
  AiSettingsTest = "ai:settings-test",
  AiModelsList = "ai:models-list",
  AiAnalyzePrompt = "ai:analyze-prompt",
  AiPreparePromptEntry = "ai:prepare-prompt-entry",
  AiOptimizePrompt = "ai:optimize-prompt",
  AiSummarizePromptTitle = "ai:summarize-prompt-title",
  AiTranslatePrompt = "ai:translate-prompt",
  AiReverseImagePrompt = "ai:reverse-image-prompt",
  AiGenerateImages = "ai:generate-images",
  DoubaoWebCanvasPrepare = "doubao-web:prepare",
  DoubaoWebCanvasAuth = "doubao-web:auth",
  DoubaoWebCanvasBounds = "doubao-web:bounds",
  DoubaoWebCanvasShow = "doubao-web:show",
  DoubaoWebCanvasHide = "doubao-web:hide",
  DoubaoWebCanvasGenerate = "doubao-web:generate",
  WebAssistantPrepare = "web-assistant:prepare",
  WebAssistantBounds = "web-assistant:bounds",
  WebAssistantShow = "web-assistant:show",
  WebAssistantVisibility = "web-assistant:visibility",
  WebAssistantCapture = "web-assistant:capture",
  WebAssistantImportCapture = "web-assistant:import-capture",
  WebAssistantHide = "web-assistant:hide",
  WebAssistantDispose = "web-assistant:dispose",
  WebAssistantExecuteScript = "web-assistant:execute-script",
  ProxySettingsRead = "proxy:settings-read",
  ProxySettingsSave = "proxy:settings-save",
  ProxySettingsTest = "proxy:settings-test",
  ProxySettingsDetect = "proxy:settings-detect",
  AppAccelerationStatusRead = "app:acceleration-status-read",
  AppAccelerationSettingsSave = "app:acceleration-settings-save",
  AppOpenExternalUrl = "app:open-external-url",
  AppOpenDataDirectory = "app:open-data-directory",
  AppUpdateCheck = "app:update-check",
  AppUpdatePreferencesRead = "app:update-preferences-read",
  AppUpdatePreferencesSave = "app:update-preferences-save",
  AppRendererReady = "app:renderer-ready",
  AppStartupScreenReady = "app:startup-screen-ready",
  AppStartupLog = "app:startup-log",
  BatchDeduplicateScan = "batch:deduplicate-scan",
  BatchCompressImages = "batch:compress-images",
  BatchCompressProgress = "batch:compress-progress",
  BatchCompressVideos = "batch:compress-videos",
  BatchCompressVideoProgress = "batch:compress-video-progress",
  BatchCancelCompress = "batch:cancel-compress",
  ModuleCheckInstalled = "module:check-installed",
  ModuleInstallLocal = "module:install-local",
  ModuleInstallDownload = "module:install-download",
  ModuleInstallGithub = "module:install-github",
  ModuleInstallProgress = "module:install-progress",
  ModuleNsfwClassify = "module:nsfw-classify",
  ModuleNsfwOpenDownloadPage = "module:nsfw-open-download-page",
  ModuleNsfwRemove = "module:nsfw-remove",
  ComponentFfmpegInstallDownload = "component:ffmpeg-install-download",
  ComponentFfmpegInstallLocal = "component:ffmpeg-install-local",
  ComponentFfmpegOpenDownloadPage = "component:ffmpeg-open-download-page",
  ComponentFfmpegRemove = "component:ffmpeg-remove",
  ComponentFfmpegInstallProgress = "component:ffmpeg-install-progress",
  WindowMinimize = "window:minimize",
  WindowResize = "window:resize",
  WindowMaximizeToggle = "window:maximize-toggle",
  WindowClose = "window:close",
  WindowIsMaximized = "window:is-maximized",
  WindowMaximizeChange = "window:maximize-change",
  WindowAlwaysOnTopToggle = "window:always-on-top-toggle",
  WindowIsAlwaysOnTop = "window:is-always-on-top",
  LogExport = "log:export",
  AccountGetStatus = "account:get-status",
  AccountGetCurrentUser = "account:get-current-user",
  AccountRegisterEmail = "account:register-email",
    AccountLoginEmail = "account:login-email",
  AccountStartOAuth = "account:start-oauth",
  AccountStartOAuthLink = "account:start-oauth-link",
  AccountConfirmOAuth = "account:confirm-oauth",
  AccountSelectOAuthAvatar = "account:select-oauth-avatar",
  AccountCancelOAuth = "account:cancel-oauth",
  AccountUnlinkIdentity = "account:unlink-identity",
  AccountLogout = "account:logout",
  AccountRefresh = "account:refresh",
  AccountUpdateProfile = "account:update-profile",
  AccountChooseAvatar = "account:choose-avatar",
  AccountRemoveAvatar = "account:remove-avatar",
  AccountStatusChanged = "account:status-changed",
}

export const ipcChannels = {
  libraryRead: IpcChannelName.LibraryRead,
  librarySave: IpcChannelName.LibrarySave,
  tagOrganizationPreview: IpcChannelName.TagOrganizationPreview,
  tagOrganizationApply: IpcChannelName.TagOrganizationApply,
  tagOrganizationUndo: IpcChannelName.TagOrganizationUndo,
  librarySyncWorks: IpcChannelName.LibrarySyncWorks,
  promptList: IpcChannelName.PromptList,
  promptCreate: IpcChannelName.PromptCreate,
  promptUpdate: IpcChannelName.PromptUpdate,
  promptDelete: IpcChannelName.PromptDelete,
  promptCopy: IpcChannelName.PromptCopy,
  promptFavorite: IpcChannelName.PromptFavorite,
  promptDuplicate: IpcChannelName.PromptDuplicate,
  promptCreateMany: IpcChannelName.PromptCreateMany,
  promptClipboardRead: IpcChannelName.PromptClipboardRead,
  promptContentImageChoose: IpcChannelName.PromptContentImageChoose,
  promptContentImageSave: IpcChannelName.PromptContentImageSave,
  promptAccountRead: IpcChannelName.PromptAccountRead,
  promptReorder: IpcChannelName.PromptReorder,
  promptMoveToCategory: IpcChannelName.PromptMoveToCategory,
  promptCategoryList: IpcChannelName.PromptCategoryList,
  promptCategoryCreate: IpcChannelName.PromptCategoryCreate,
  promptCategoryUpdate: IpcChannelName.PromptCategoryUpdate,
  promptCategoryDelete: IpcChannelName.PromptCategoryDelete,
  promptCategoryReorder: IpcChannelName.PromptCategoryReorder,
  promptCategoryMerge: IpcChannelName.PromptCategoryMerge,
  promptExport: IpcChannelName.PromptExport,
  promptImport: IpcChannelName.PromptImport,
  promptGithubProjectFetch: IpcChannelName.PromptGithubProjectFetch,
  todoList: IpcChannelName.TodoList,
  todoCalendarRead: IpcChannelName.TodoCalendarRead,
  todoCalendarUpdate: IpcChannelName.TodoCalendarUpdate,
  todoHolidayYear: IpcChannelName.TodoHolidayYear,
  todoTaskCreate: IpcChannelName.TodoTaskCreate,
  todoTaskUpdate: IpcChannelName.TodoTaskUpdate,
  todoTaskDelete: IpcChannelName.TodoTaskDelete,
  todoTaskComplete: IpcChannelName.TodoTaskComplete,
  todoLibraryReplace: IpcChannelName.TodoLibraryReplace,
  todoImportFiles: IpcChannelName.TodoImportFiles,
  todoExport: IpcChannelName.TodoExport,
  todoImportLibraries: IpcChannelName.TodoImportLibraries,
  todoProjectCreate: IpcChannelName.TodoProjectCreate,
  todoProjectUpdate: IpcChannelName.TodoProjectUpdate,
  todoProjectDelete: IpcChannelName.TodoProjectDelete,
  todoProjectReorder: IpcChannelName.TodoProjectReorder,
  todoWidgetCreate: IpcChannelName.TodoWidgetCreate,
  todoWidgetUpdate: IpcChannelName.TodoWidgetUpdate,
  todoWidgetDelete: IpcChannelName.TodoWidgetDelete,
  todoWidgetReorder: IpcChannelName.TodoWidgetReorder,
  libraryViewSettingsRead: IpcChannelName.LibraryViewSettingsRead,
  libraryViewSettingsSave: IpcChannelName.LibraryViewSettingsSave,
  themeBackgroundChoose: IpcChannelName.ThemeBackgroundChoose,
  themeBackgroundRemove: IpcChannelName.ThemeBackgroundRemove,
  libraryRootsList: IpcChannelName.LibraryRootsList,
  libraryRootOrderSet: IpcChannelName.LibraryRootOrderSet,
  libraryRootChooseAndScan: IpcChannelName.LibraryRootChooseAndScan,
  libraryDirectoryChooseAndImport: IpcChannelName.LibraryDirectoryChooseAndImport,
  libraryRootScan: IpcChannelName.LibraryRootScan,
  libraryRootRemap: IpcChannelName.LibraryRootRemap,
  libraryRootRemove: IpcChannelName.LibraryRootRemove,
  libraryRootPurgeMissing: IpcChannelName.LibraryRootPurgeMissing,
  libraryRootWatchSet: IpcChannelName.LibraryRootWatchSet,
  libraryExternalChanged: IpcChannelName.LibraryExternalChanged,
  libraryExternalValidate: IpcChannelName.LibraryExternalValidate,
  startupGalleryList: IpcChannelName.StartupGalleryList,
  startupGalleryImport: IpcChannelName.StartupGalleryImport,
  startupGalleryImportFromClipboard: IpcChannelName.StartupGalleryImportFromClipboard,
  startupGalleryRemove: IpcChannelName.StartupGalleryRemove,
  startupGalleryReset: IpcChannelName.StartupGalleryReset,
  imageImportFiles: IpcChannelName.ImageImportFiles,
  imageImportFilesForItem: IpcChannelName.ImageImportFilesForItem,
  imageImportBuffers: IpcChannelName.ImageImportBuffers,
  imageImportGenerated: IpcChannelName.ImageImportGenerated,
  imageImportProgress: IpcChannelName.ImageImportProgress,
  imageImportCancel: IpcChannelName.ImageImportCancel,
  wordDocumentImport: IpcChannelName.WordDocumentImport,
  imageImportFromClipboard: IpcChannelName.ImageImportFromClipboard,
  imageImportClipboardForItem: IpcChannelName.ImageImportClipboardForItem,
  imageRemoteMaterialDownload: IpcChannelName.ImageRemoteMaterialDownload,
  imageCopy: IpcChannelName.ImageCopy,
  imageExport: IpcChannelName.ImageExport,
  imageThumbnailResolve: IpcChannelName.ImageThumbnailResolve,
  imageThumbnailsResolve: IpcChannelName.ImageThumbnailsResolve,
  imageGetFileSize: IpcChannelName.ImageGetFileSize,
  clipboardWriteText: IpcChannelName.ClipboardWriteText,
  clipboardReadText: IpcChannelName.ClipboardReadText,
  clipboardReadImage: IpcChannelName.ClipboardReadImage,
  canvasReferenceImageSave: IpcChannelName.CanvasReferenceImageSave,
  canvasReferenceImageRead: IpcChannelName.CanvasReferenceImageRead,
  canvasReferenceImageRemove: IpcChannelName.CanvasReferenceImageRemove,
  lexiconImageImport: IpcChannelName.LexiconImageImport,
  lexiconExport: IpcChannelName.LexiconExport,
  lexiconImport: IpcChannelName.LexiconImport,
  itemDelete: IpcChannelName.ItemDelete,
  videoFramesGenerate: IpcChannelName.VideoFramesGenerate,
  videoReferenceImagesImport: IpcChannelName.VideoReferenceImagesImport,
  videoReferenceImageDelete: IpcChannelName.VideoReferenceImageDelete,
  videoReferenceImageImportClipboard: IpcChannelName.VideoReferenceImageImportClipboard,
  videoReferenceImageImportUrl: IpcChannelName.VideoReferenceImageImportUrl,
  archiveExportZip: IpcChannelName.ArchiveExportZip,
  archiveImportZip: IpcChannelName.ArchiveImportZip,
  aiSettingsRead: IpcChannelName.AiSettingsRead,
  aiSettingsSave: IpcChannelName.AiSettingsSave,
  aiSettingsExport: IpcChannelName.AiSettingsExport,
  aiSettingsImport: IpcChannelName.AiSettingsImport,
  aiSettingsImportApply: IpcChannelName.AiSettingsImportApply,
  aiApiKeyCopy: IpcChannelName.AiApiKeyCopy,
  aiApiKeyRead: IpcChannelName.AiApiKeyRead,
  aiSettingsTest: IpcChannelName.AiSettingsTest,
  aiModelsList: IpcChannelName.AiModelsList,
  aiAnalyzePrompt: IpcChannelName.AiAnalyzePrompt,
  aiPreparePromptEntry: IpcChannelName.AiPreparePromptEntry,
  aiOptimizePrompt: IpcChannelName.AiOptimizePrompt,
  aiSummarizePromptTitle: IpcChannelName.AiSummarizePromptTitle,
  aiTranslatePrompt: IpcChannelName.AiTranslatePrompt,
  aiReverseImagePrompt: IpcChannelName.AiReverseImagePrompt,
  aiGenerateImages: IpcChannelName.AiGenerateImages,
  doubaoWebCanvasPrepare: IpcChannelName.DoubaoWebCanvasPrepare,
  doubaoWebCanvasAuth: IpcChannelName.DoubaoWebCanvasAuth,
  doubaoWebCanvasBounds: IpcChannelName.DoubaoWebCanvasBounds,
  doubaoWebCanvasShow: IpcChannelName.DoubaoWebCanvasShow,
  doubaoWebCanvasHide: IpcChannelName.DoubaoWebCanvasHide,
  doubaoWebCanvasGenerate: IpcChannelName.DoubaoWebCanvasGenerate,
  webAssistantPrepare: IpcChannelName.WebAssistantPrepare,
  webAssistantBounds: IpcChannelName.WebAssistantBounds,
  webAssistantShow: IpcChannelName.WebAssistantShow,
  webAssistantVisibility: IpcChannelName.WebAssistantVisibility,
  webAssistantCapture: IpcChannelName.WebAssistantCapture,
  webAssistantImportCapture: IpcChannelName.WebAssistantImportCapture,
  webAssistantHide: IpcChannelName.WebAssistantHide,
  webAssistantDispose: IpcChannelName.WebAssistantDispose,
  webAssistantExecuteScript: IpcChannelName.WebAssistantExecuteScript,
  proxySettingsRead: IpcChannelName.ProxySettingsRead,
  proxySettingsSave: IpcChannelName.ProxySettingsSave,
  proxySettingsTest: IpcChannelName.ProxySettingsTest,
  proxySettingsDetect: IpcChannelName.ProxySettingsDetect,
  appAccelerationStatusRead: IpcChannelName.AppAccelerationStatusRead,
  appAccelerationSettingsSave: IpcChannelName.AppAccelerationSettingsSave,
  appOpenExternalUrl: IpcChannelName.AppOpenExternalUrl,
  appOpenDataDirectory: IpcChannelName.AppOpenDataDirectory,
  appUpdateCheck: IpcChannelName.AppUpdateCheck,
  appUpdatePreferencesRead: IpcChannelName.AppUpdatePreferencesRead,
  appUpdatePreferencesSave: IpcChannelName.AppUpdatePreferencesSave,
  appRendererReady: IpcChannelName.AppRendererReady,
  appStartupScreenReady: IpcChannelName.AppStartupScreenReady,
  appStartupLog: IpcChannelName.AppStartupLog,
  batchDeduplicateScan: IpcChannelName.BatchDeduplicateScan,
  batchCompressImages: IpcChannelName.BatchCompressImages,
  batchCompressProgress: IpcChannelName.BatchCompressProgress,
  batchCompressVideos: IpcChannelName.BatchCompressVideos,
  batchCompressVideoProgress: IpcChannelName.BatchCompressVideoProgress,
  batchCancelCompress: IpcChannelName.BatchCancelCompress,
  moduleCheckInstalled: IpcChannelName.ModuleCheckInstalled,
  moduleInstallLocal: IpcChannelName.ModuleInstallLocal,
  moduleInstallDownload: IpcChannelName.ModuleInstallDownload,
  moduleInstallGithub: IpcChannelName.ModuleInstallGithub,
  moduleInstallProgress: IpcChannelName.ModuleInstallProgress,
  moduleNsfwClassify: IpcChannelName.ModuleNsfwClassify,
  moduleNsfwOpenDownloadPage: IpcChannelName.ModuleNsfwOpenDownloadPage,
  moduleNsfwRemove: IpcChannelName.ModuleNsfwRemove,
  componentFfmpegInstallDownload: IpcChannelName.ComponentFfmpegInstallDownload,
  componentFfmpegInstallLocal: IpcChannelName.ComponentFfmpegInstallLocal,
  componentFfmpegOpenDownloadPage: IpcChannelName.ComponentFfmpegOpenDownloadPage,
  componentFfmpegRemove: IpcChannelName.ComponentFfmpegRemove,
  componentFfmpegInstallProgress: IpcChannelName.ComponentFfmpegInstallProgress,
  windowMinimize: IpcChannelName.WindowMinimize,
  windowResize: IpcChannelName.WindowResize,
  windowMaximizeToggle: IpcChannelName.WindowMaximizeToggle,
  windowClose: IpcChannelName.WindowClose,
  windowIsMaximized: IpcChannelName.WindowIsMaximized,
  windowMaximizeChange: IpcChannelName.WindowMaximizeChange,
  windowAlwaysOnTopToggle: IpcChannelName.WindowAlwaysOnTopToggle,
  windowIsAlwaysOnTop: IpcChannelName.WindowIsAlwaysOnTop,
  logExport: IpcChannelName.LogExport,
  accountGetStatus: IpcChannelName.AccountGetStatus,
  accountGetCurrentUser: IpcChannelName.AccountGetCurrentUser,
  accountRegisterEmail: IpcChannelName.AccountRegisterEmail,
    accountLoginEmail: IpcChannelName.AccountLoginEmail,
  accountStartOAuth: IpcChannelName.AccountStartOAuth,
  accountStartOAuthLink: IpcChannelName.AccountStartOAuthLink,
  accountConfirmOAuth: IpcChannelName.AccountConfirmOAuth,
  accountSelectOAuthAvatar: IpcChannelName.AccountSelectOAuthAvatar,
  accountCancelOAuth: IpcChannelName.AccountCancelOAuth,
  accountUnlinkIdentity: IpcChannelName.AccountUnlinkIdentity,
  accountLogout: IpcChannelName.AccountLogout,
  accountRefresh: IpcChannelName.AccountRefresh,
  accountUpdateProfile: IpcChannelName.AccountUpdateProfile,
  accountChooseAvatar: IpcChannelName.AccountChooseAvatar,
  accountRemoveAvatar: IpcChannelName.AccountRemoveAvatar,
  accountStatusChanged: IpcChannelName.AccountStatusChanged,
} as const;

export type IpcChannel = (typeof ipcChannels)[keyof typeof ipcChannels];
